server:
  port: 5555
spring:
  application:
    name: api-gateway
zuul:
  routes:
    api-a-url:
      path: /api-a-url/**
      serviceId: eureka-consumer
    api-b-url:
          path: /api-b-url/**
          serviceId: feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
